name: Auth

on:
  push:
    branches: [ main ]
    paths:
    - 'auth/**'
    - 'internal/**'
    - 'go.mod'
    - 'go.sum'
    - '.github/workflows/auth.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'auth/**'
    - 'internal/**'
    - 'go.mod'
    - 'go.sum'
    - '.github/workflows/auth.yml'
  release:
    types: [ created ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/auth:${{ github.sha }}
          ${{ github.event_name == 'release' && format('ghcr.io/{0}/auth:{1}', github.repository, github.ref_name) || '' }}
          ${{ github.event_name == 'release' && 'ghcr.io/${{ github.repository }}/auth:latest' || '' }}
