name: Build/Release dlqtools

on:
  push:
    branches: [ main ]
    paths:
    - 'cmd/dlqtools/**'
    - 'internal/**'
    - 'go.mod'
    - 'go.sum'
    - '.github/workflows/build.yml'
  release:
    types: [ created ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64 ]
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Build
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dlqtools-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/dlqtools
        if [ "${{ matrix.goos }}" = "windows" ]; then
          mv dlqtools-${{ matrix.goos }}-${{ matrix.goarch }} dlqtools-${{ matrix.goos }}-${{ matrix.goarch }}.exe
        fi

    - name: Upload binary to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: dlqtools-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
