name: Build and Release dlqtools

on:
  push:
    branches: [ main ]
    paths:
    - 'cmd/dlqtools/**'
    - 'internal/**'
    - 'go.mod'
    - 'go.sum'
    - '.github/workflows/build.yml'
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64 ]
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Build
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dlqtools-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/dlqtools
        if [ "${{ matrix.goos }}" = "windows" ]; then
          mv dlqtools-${{ matrix.goos }}-${{ matrix.goarch }} dlqtools-${{ matrix.goos }}-${{ matrix.goarch }}.exe
        fi

    - name: Upload binary to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dlqtools-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
        asset_name: dlqtools-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
        asset_content_type: application/octet-stream
